#!/usr/bin/env bash
#
#  aetherisd The aetheris more server.
#
#
# chkconfig: 345 80 20
# description: aetherisd
# processname: aetherisd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/aetherisd, see below
if [ -f /etc/sysconfig/aetherisd ]; then
        . /etc/sysconfig/aetherisd
fi

RETVAL=0

prog=aetherisd
# you can override the lockfile via BLACKMORED_LOCKFILE in /etc/sysconfig/aetherisd
lockfile=${BLACKMORED_LOCKFILE-/var/lock/subsys/aetherisd}

# aetherisd defaults to /usr/bin/aetherisd, override with BLACKMORED_BIN
aetherisd=${BLACKMORED_BIN-/usr/bin/aetherisd}

# aetherisd opts default to -disablewallet, override with BLACKMORED_OPTS
aetherisd_opts=${BLACKMORED_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $bitcoind $bitcoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
